/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
#include <opencv2/opencv.hpp>

using namespace cv;
using namespace std;
/* Header for class com_example_suman_uniquepausefinal_ViolaJonesAlgorithm_OpencvClass */

#ifndef _Included_com_example_suman_uniquepausefinal_ViolaJonesAlgorithm_OpencvClass
#define _Included_com_example_suman_uniquepausefinal_ViolaJonesAlgorithm_OpencvClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_suman_uniquepausefinal_ViolaJonesAlgorithm_OpencvClass
 * Method:    faceDetection
 * Signature: (J)I
 */
int detectFace(Mat& frame);
JNIEXPORT jint JNICALL Java_com_example_suman_uniquepausefinal_ViolaJonesAlgorithm_OpencvClass_faceDetection
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
